var test = ``;

document.write('<script src="https://namgd.com/projects/mocnguyen/js/jquery-1.12.4.min.js"></script>');
document.write('<script src="https://namgd.com/projects/mocnguyen/js/bootstrap.min.js"></script>');
document.write('<script src="https://namgd.com/projects/mocnguyen/js/jquery.fancybox.pack.js"></script>');
document.write('<script src="https://namgd.com/projects/mocnguyen/js/jquery.fancybox-media.js"></script>');
document.write('<script src="https://namgd.com/projects/mocnguyen/js/slick.js"></script>');
document.write('<script src="https://namgd.com/projects/mocnguyen/js/jquery.countTo.js"></script>');
document.write('<script src="https://namgd.com/projects/mocnguyen/js/validate.js"></script>');
document.write('<script type="text/javascript" src="https://namgd.com/projects/mocnguyen/js/revolution/jquery.themepunch.tools.min.js"></script>');
document.write('<script type="text/javascript" src="https://namgd.com/projects/mocnguyen/js/revolution/jquery.themepunch.revolution.min.js"></script>');
document.write('<script type="text/javascript" src="https://namgd.com/projects/mocnguyen/js/revolution/extensions/revolution.extension.actions.min.js"></script>');
document.write('<script type="text/javascript" src="https://namgd.com/projects/mocnguyen/js/revolution/extensions/revolution.extension.carousel.min.js"></script>');
document.write('<script type="text/javascript" src="https://namgd.com/projects/mocnguyen/js/revolution/extensions/revolution.extension.kenburn.min.js"></script>');
document.write('<script type="text/javascript" src="https://namgd.com/projects/mocnguyen/js/revolution/extensions/revolution.extension.layeranimation.min.js"></script>');
document.write('<script type="text/javascript" src="https://namgd.com/projects/mocnguyen/js/revolution/extensions/revolution.extension.migration.min.js"></script>');
document.write('<script type="text/javascript" src="https://namgd.com/projects/mocnguyen/js/revolution/extensions/revolution.extension.navigation.min.js"></script>');
document.write('<script type="text/javascript" src="https://namgd.com/projects/mocnguyen/js/revolution/extensions/revolution.extension.parallax.min.js"></script>');
document.write('<script type="text/javascript" src="https://namgd.com/projects/mocnguyen/js/revolution/extensions/revolution.extension.slideanims.min.js"></script>');
document.write('<script type="text/javascript" src="https://namgd.com/projects/mocnguyen/js/revolution/extensions/revolution.extension.video.min.js"></script>');
document.write('<script src="https://namgd.com/projects/mocnguyen/js/scripts.min.js"></script>');
// document.write('<script src="https://namgd.com/projects/mocnguyen/js/header.js"></script>');
// document.write('<script src="https://namgd.com/projects/mocnguyen/js/primary-mobile-nav.js"></script>');
// document.write('<script src="https://namgd.com/projects/mocnguyen/js/footer-widgets.js"></script>');
// document.write('<script src="https://namgd.com/projects/mocnguyen/js/footer-widgets-middle.js"></script>');
// document.write('<script src="https://namgd.com/projects/mocnguyen/js/colophon.js"></script>');
document.write('<script src="https://namgd.com/projects/mocnguyen/js/script.js"></script>');
